"""alter_company_size_to_string

Revision ID: 0b7194cb1068
Revises: 7505a3b6f6ab
Create Date: 2026-07-01 21:17:31.520799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0b7194cb1068'
down_revision: Union[str, None] = '7505a3b6f6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_followups_scheduled_at")
    op.alter_column('applications', 'profile_email_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.execute("DROP INDEX IF EXISTS uq_app_sender_scheduled_at")
    op.execute("DROP INDEX IF EXISTS uq_applications_job_profile")
    op.alter_column('job_activities', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("DROP INDEX IF EXISTS ix_job_activities_created_at")
    op.execute("DROP INDEX IF EXISTS ix_job_activities_job_id")
    op.execute("DROP INDEX IF EXISTS ix_job_activities_user_id")
    op.alter_column('jobs', 'company_size',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('jobs', 'auto_apply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'auto_apply_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'company_size',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_job_activities_user_id'), 'job_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_activities_job_id'), 'job_activities', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_activities_created_at'), 'job_activities', ['created_at'], unique=False)
    op.alter_column('job_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_activities', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('uq_applications_job_profile'), 'applications', ['job_id', 'profile_id'], unique=True, postgresql_where='(job_id IS NOT NULL)')
    op.create_index(op.f('uq_app_sender_scheduled_at'), 'applications', ['sender_email', 'scheduled_at'], unique=True, postgresql_where="((status = ANY (ARRAY['scheduled'::applicationstatus, 'pending_approval'::applicationstatus])) AND (sent_at IS NULL))")
    op.alter_column('applications', 'profile_email_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('uq_followups_scheduled_at'), 'application_followups', ['scheduled_at'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'sending'::character varying])::text[]))")
    # ### end Alembic commands ###
